env:
  browser: true
  es2021: true
  mocha: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'chai-friendly'
rules: {
  "no-unused-expressions": 0,
  "chai-friendly/no-unused-expressions": 2
}
